# Generated by Django 5.2.9 on 2025-12-26 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='title')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('publish_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='publication start')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_start'],
            },
        ),
    ]
